### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by KolbJL** [psu-spatial/Stat462-2024#11]
<img width="667" alt="Screenshot 2024-01-24 at 4 19 37 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/157649651/eb8b9c68-d096-4687-8f50-31e2b3f1b245">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
