### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Dnt5147** [psu-spatial/Stat462-2024#13]
![Screenshot 2024-01-24 180439](https://github.com/psu-spatial/Stat462-2024/assets/157649590/a71dcbb4-f4c7-468f-8bd3-39fc101f118f)

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
