### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Abeermathur7** [psu-spatial/Stat462-2024#16]
<img width="631" alt="image" src="https://github.com/psu-spatial/Stat462-2024/assets/66336010/3f39e905-2196-4b4b-9d06-254ecf4664c5">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
