### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Austinma7792** [psu-spatial/Stat462-2024#17]
<img width="647" alt="Screen Shot 2024-01-29 at 2 20 42 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/157648664/b0990851-4fae-4822-bdd0-9491088865c8">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
