### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by tylerh427** [psu-spatial/Stat462-2024#18]
![Screenshot 2024-01-31 143319](https://github.com/psu-spatial/Stat462-2024/assets/158342053/f2ee9973-f81b-414e-ad08-de199f636d63)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
