### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by JHotalski** [psu-spatial/Stat462-2024#19]
<img width="588" alt="Screenshot 2024-01-31 at 2 36 54 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/158333293/6b80042b-80e2-4cb2-99c1-7d8102fbf76e">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
