### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by tarynmch** [psu-spatial/Stat462-2024#2]
<img width="368" alt="Screenshot 2024-01-24 154403" src="https://github.com/psu-spatial/Stat462-2024/assets/119536819/1d6335d1-f038-46fd-a918-3fabe240a639">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
