### ISSUE TITLE
Hello from O!

### ISSUE THREAD

**Issue by lackingtoast** [psu-spatial/Stat462-2024#20]
<img width="1440" alt="Screenshot 2024-01-31 at 3 33 40 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/158351020/ec2648eb-94f4-4c2d-864a-2e7dadccb7c4">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
