### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by dvdsms1** [psu-spatial/Stat462-2024#21]
<img width="1440" alt="Screen Shot 2024-01-31 at 3 40 26 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/158351310/ed5e73f1-f2b0-4b67-871a-099c11efe102">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
