### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by mzk5991** [psu-spatial/Stat462-2024#23]
Greetings! 

<img width="1512" alt="Screenshot 2024-01-31 at 15 43 45" src="https://github.com/psu-spatial/Stat462-2024/assets/144627049/bdc3d446-7ec0-4d2a-8003-8cb19a75c925">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
