### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Andrew26096** [psu-spatial/Stat462-2024#24]
![Screenshot 2024-01-31 155451](https://github.com/psu-spatial/Stat462-2024/assets/157648580/274aac22-5e99-472d-b69f-faf3e8c46778)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
