### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Qiankong233** [psu-spatial/Stat462-2024#25]
<img width="1093" alt="截屏2024-01-31 下午3 55 55" src="https://github.com/psu-spatial/Stat462-2024/assets/112832656/55e5e1d1-3273-40e7-bc8e-6ede79147cd7">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
