### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by beckymurphy** [psu-spatial/Stat462-2024#26]
Hello
![Screenshot 2024-01-31 155854](https://github.com/psu-spatial/Stat462-2024/assets/158354473/dcfad980-4eea-42a1-ad32-dbd5702677ff)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
