### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by MaryFick** [psu-spatial/Stat462-2024#27]
<img width="498" alt="Screenshot 2024-01-31 at 4 01 46 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/158354510/2e570e8b-34d2-4774-81c9-5f4fe34e0ad5">

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
