### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by KeTang77** [psu-spatial/Stat462-2024#28]
![Screenshot 2024-01-31 160857](https://github.com/psu-spatial/Stat462-2024/assets/158355226/be914c0e-0f15-42e4-8fb3-ed668783e8c4)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
