### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Z-Zhng** [psu-spatial/Stat462-2024#29]
![Screenshot 2024-01-31 161727](https://github.com/psu-spatial/Stat462-2024/assets/158355781/a857d53e-9d7b-4667-8ec6-a0565648b14a)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
