### ISSUE TITLE
Lab2 Test Issue

### ISSUE THREAD

**Issue by ChulickM** [psu-spatial/Stat462-2024#3]
Hi

![Lab2](https://github.com/psu-spatial/Stat462-2024/assets/113074265/7c0aad8e-9949-47f8-8682-ee154599dfc7)

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
