### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Minu-Oh** [psu-spatial/Stat462-2024#30]
![Screenshot 2024-02-01 at 10 53 37](https://github.com/psu-spatial/Stat462-2024/assets/129083631/b63201f8-15b6-4dfa-9b36-ad93667fd106)

**Comment by hgreatrex** [comment]
Hello!  
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well!  Dr G
