### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by aboudazz** [psu-spatial/Stat462-2024#38]
<img width="930" alt="Screen Shot 2024-02-02 at 2 41 54 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/157648601/6bac7db9-dcf2-4139-90e6-e87b06fc9484">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
