### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Mdemi25** [psu-spatial/Stat462-2024#39]
<img width="1440" alt="Screen Shot 2024-02-02 at 3 33 24 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/158618837/b9ce7853-f65e-486d-9829-5e1533f8fb8d">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
