### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by nicocardenasmiller** [psu-spatial/Stat462-2024#4]
<img width="1440" alt="Screenshot 2024-01-24 at 3 46 42 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/157647237/eeec8404-368b-4781-b71a-4fbdbfc991a4">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
