### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by BingdaChen** [psu-spatial/Stat462-2024#40]
<img width="529" alt="截屏2024-02-02 下午5 13 56" src="https://github.com/psu-spatial/Stat462-2024/assets/157846120/81d687e1-a344-4cfd-b9db-3890cebebb9c">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
