### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mdiehl192** [psu-spatial/Stat462-2024#44]
![Screenshot 2024-02-02 192326](https://github.com/psu-spatial/Stat462-2024/assets/158637546/ee536d7b-aa24-4db4-9532-99635d5746f7)

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
