### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by SUE141319** [psu-spatial/Stat462-2024#45]
not sure whether I do it correctly
<img width="457" alt="Screenshot 2024-02-02 193908" src="https://github.com/psu-spatial/Stat462-2024/assets/158520375/ab9b773a-18f6-4a16-8328-ee326a0e29b1">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
