### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Khadijah132** [psu-spatial/Stat462-2024#46]
![Screenshot 2024-02-02 220858](https://github.com/psu-spatial/Stat462-2024/assets/129332060/6ad6c7e0-e964-4fec-85f3-875f3c50a62e)

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well! Dr G
