### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by LLInkpen** [psu-spatial/Stat462-2024#5]
![Screenshot 2024-01-24 154614](https://github.com/psu-spatial/Stat462-2024/assets/119536799/b8c3b126-c6e1-443a-9d83-448f8de5282b)

**Comment by hgreatrex** [comment]
I have the same problem

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
