### ISSUE TITLE
Remote library

### ISSUE THREAD

**Issue by Z-Zhng** [psu-spatial/Stat462-2024#55]
![Screenshot 2024-04-03 154850](https://github.com/psu-spatial/Stat462-2024/assets/158355781/28322686-268e-4d0a-ac2f-fcfe215ab62f)

I cant find nor install the remote library.

**Comment by aboudazz** [comment]
The error message you are encountering indicates that the R package remotes is not installed on your system. Follow these
1. Install the remotes package: install.packages("remotes")
2. Load the remotes package: library(remotes)

**Comment by hgreatrex** [comment]
Thanks - we solved this during the lab and forgot to mark it as complete
