### ISSUE TITLE
Bad Credentials

### ISSUE THREAD

**Issue by LLInkpen** [psu-spatial/Stat462-2024#56]
![image](https://github.com/psu-spatial/Stat462-2024/assets/119536799/e811738c-c580-4460-8988-0488885359b3)

I was able to install the remotes package but get an error when installing from github

**Comment by aboudazz** [comment]
From the error message, it seems like there are a couple of issues to address:

1. Rtools is not installed: The warning message indicates that Rtools is not installed. Rtools is a collection of command-line tools to facilitate R development on Windows. Some packages require Rtools to build from source. You can download Rtools from CRAN and install it on your system. 
2. Bad credentials (HTTP error 401): This error message suggests that the GitHub Personal Access Token (PAT) being used is either incorrect, expired, or does not have the required permissions. This could happen if there was an error during the creation of the PAT or if the PAT has been revoked or expired. You will need to generate a new PAT from your GitHub account with the correct scopes (permissions) required to install packages.

**Comment by hgreatrex** [comment]
I think we tried to address this during the lab
For those who need them, here are the PAT instructions, https://github.com/r-lib/devtools/issues/1566
and other reasons for this are that Rstudio itself or R needed updating.
