### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by OZC5073** [psu-spatial/Stat462-2024#6]
Lab 2 Test Issue: 
<img width="465" alt="Screen Shot 2024-01-24 at 3 56 21 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/157647678/43ce49df-9d66-4d92-847a-dcb7f4acaf74">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
