### ISSUE TITLE
Hello from Albert Wang

### ISSUE THREAD

**Issue by AlbertWang0930** [psu-spatial/Stat462-2024#8]
Hello
<img width="838" alt="code" src="https://github.com/psu-spatial/Stat462-2024/assets/157649008/54abb553-e33a-4d27-b985-aec78066f467">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
