### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ajk6876** [psu-spatial/Stat462-2024#9]
<img width="915" alt="Screen Shot 2024-01-24 at 4 12 43 PM" src="https://github.com/psu-spatial/Stat462-2024/assets/149616038/994acbbe-34f4-4f34-98c0-435dc0e6c80d">

**Comment by hgreatrex** [comment]
Hello!
Closing this now - but know that you can either ask R questions for help here, or you can check to see if anyone has had the same issue
Hope all is well, Dr G
